### ISSUE TITLE
Compile error on Ubuntu 18.04

### ISSUE THREAD

**Issue by afonsolage** [Zylann/godot_voxel#38]
Hello folks,

When trying to compile on Ubuntu 18.04, I got the following compile error with GCC 7.4.0:
```
modules/voxel/meshers/dmc/voxel_mesher_dmc.cpp: In member function 'virtual void VoxelMesherDMC::build(VoxelMesher::Output&, const VoxelBuffer&, int)':
modules/voxel/meshers/dmc/voxel_mesher_dmc.cpp:1469:15: error: no match for 'operator=' (operand types are 'VoxelMesherDMC::Stats' and '<brace-enclosed initializer list>')
  _stats = { 0 };
```

After changing this line of code on **/modules/voxel/meshers/dmc/voxel_mesher_dmc.cpp(1469)**:
```
_stats = { 0 };
```
To:
```
_stats = {};

```
It worked fine.

**Comment by afonsolage** [comment]
Tried on Windows 10 and it worked fine.

**Comment by tinmanjuggernaut** [comment]
Strange. I wonder if something happened upstream with Godot. A couple months ago I went through a bunch of changes to get it to compile on gcc 8.3 (lubuntu) and 8.1 (mingw) without warnings. Nothing has changed in VT or my setup, but now I also get this error.

I have read that though initiazling a struct with { 0 } is valid C since [C90](https://en.cppreference.com/w/c/language/struct_initialization), but apparently { } is the proper C++ way as of [C++11](https://en.cppreference.com/w/cpp/language/zero_initialization).
