### ISSUE TITLE
Fails to compile on ubuntu 16.04 with godot 2.1

### ISSUE THREAD

**Issue by cyian-1756** [Zylann/godot_voxel#3]
Trying to compile this on ubuntu 16.04 with godot 2.2 errors out with 

```scons: done reading SConscript files.
scons: Building targets ...
g++ -o modules/register_module_types.x11.tools.64.o -c -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DENABLE_DEPRECATED -DOPENGL_ENABLED -DALSA_ENABLED -DJOYDEV_ENABLED -DPULSEAUDIO_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DGLES_OVER_GL -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DGLEW_ENABLED -DGLEW_STATIC -DOPENSSL_ENABLED -DMODULE_CSCRIPT_ENABLED -DMODULE_ENET_ENABLED -DMODULE_GDNET_ENABLED -DMODULE_GDSCRIPT_ENABLED -DMODULE_GODOT_VOXEL_ENABLED -DMODULE_GRIDMAP_ENABLED -DMODULE_IK_ENABLED -DMODULE_VISUAL_SCRIPT_ENABLED -D_REENTRANT -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/x11 -I/usr/include/freetype2 -I/usr/include/alsa -Imodules modules/register_module_types.cpp
modules/register_module_types.cpp: In function 'void register_module_types()':
modules/register_module_types.cpp:31:29: error: 'register_godot_voxel_types' was not declared in this scope
  register_godot_voxel_types();
                             ^
modules/register_module_types.cpp: In function 'void unregister_module_types()':
modules/register_module_types.cpp:61:31: error: 'unregister_godot_voxel_types' was not declared in this scope
  unregister_godot_voxel_types();
                               ^
scons: *** [modules/register_module_types.x11.tools.64.o] Error 1
scons: building terminated because of errors.```

**Comment by Zylann** [comment]
I compiled it recently for 2.1 master and it worked. I have no idea of what's going on in 2.2 Oo

**Comment by cyian-1756** [comment]
> I have no idea of what's going on in 2.2

@Zylann neither do I, of the 3 voxel terrain modules I've tried all have failed to compile in 2.2 with more or less the same error. I'll down grade to 2.1 later on tomorrow and see if that works

**Comment by Zylann** [comment]
What do you call 2.2? I don't see this branch on Godot Github.

**Comment by cyian-1756** [comment]
@Zylann Sorry about that, it seems to be 2.1 but for some reason the version godot reports is 2.2. The branch I cloned and compiled from (Which doesn't work with godot_voxel) is 2.1

**Comment by cyian-1756** [comment]
@Zylann Just tried to compile with 2.0 and it fails with the same error

**Comment by Zylann** [comment]
I'll try to compile it when I get back home

**Comment by Zylann** [comment]
Aaaahhh I should have seen that from the beginning:

The error you get happens in modules/register_module_types.cpp:61:31.
This file is not part of my module, it's supposed to have been generated by SCons.

For some reason, I also noticed another module I'm making doesn't appears as well in this file, and I have no idea why...

**Comment by Zylann** [comment]
Got it: you have to name the module's folder "voxel", not "godot_voxel".

The reason why is that Godot SCons scripts are detecting the directory name as the module name. But of course the repo name doesn't matches, because I choosed it as... well, a Github repo name. 
That's annoying, but it should fix your problem :)

**Comment by cyian-1756** [comment]
@Zylann  That has fixed the first issue but I've seem to have run into a new one. Now when I try to compile I get the following error

```modules/voxel/voxel_terrain.cpp: In member function 'void VoxelTerrain::update_blocks()':
modules/voxel/voxel_terrain.cpp:97:32: warning: unused variable 'err' [-Wunused-variable]
             Variant::CallError err; // wut
                                ^
In file included from core/resource.h:35:0,
                 from core/script_language.h:32,
                 from ./scene/main/node.h:36,
                 from modules/voxel/voxel_terrain.h:4,
                 from modules/voxel/voxel_terrain.cpp:1:
core/reference.h: In instantiation of 'void Ref<T>::unref() [with T = VoxelLibrary]':
core/reference.h:308:8:   required from 'Ref<T>::~Ref() [with T = VoxelLibrary]'
modules/voxel/voxel_mesher.h:12:7:   required from 'void memdelete(T*) [with T = VoxelMesher]'
core/reference.h:292:13:   required from 'void Ref<T>::unref() [with T = VoxelMesher]'
core/reference.h:308:8:   required from 'Ref<T>::~Ref() [with T = VoxelMesher]'
modules/voxel/voxel_terrain.h:30:44:   required from here
core/reference.h:290:17: error: invalid use of incomplete type 'class VoxelLibrary'
   if (reference && reference->unreference()) {
                 ^
In file included from modules/voxel/voxel_mesher.h:7:0,
                 from modules/voxel/voxel_terrain.h:6,
                 from modules/voxel/voxel_terrain.cpp:1:
modules/voxel/voxel.h:6:7: note: forward declaration of 'class VoxelLibrary'
 class VoxelLibrary;```

**Comment by Zylann** [comment]
I deleted all .obj files and compiled again the module, I don't get this error :/

**Comment by cyian-1756** [comment]
@Zylann They aren't any objs in /modules

**Comment by Zylann** [comment]
Yeah sorry I was talking about the binary files generated by the compiler, they are .o or .a with other ones.

**Comment by cyian-1756** [comment]
@Zylann I deleted all .a and .o files from my godot dir and ran into the same issue when compiling

**Comment by Zylann** [comment]
Yeah I just meant "I cleaned and build".
Anyways, I also tried to completely remove the module from my project, re-clone it from Github, compile it out of the box with the engine... and no error. There is something strange going on Oo

**Comment by cyian-1756** [comment]
I'm going to reclone this and godot and see if it will build then

**Comment by cyian-1756** [comment]
@Zylann It still fails to build. What platform are you building on and with what compiler?

**Comment by Zylann** [comment]
I'm building on Windows with Visual Studio 2015.

**Comment by cyian-1756** [comment]
I tried building for windows using and got the same error and I tried building using clang and got a new error

```core/reference.h:290:29: error: member access into incomplete type
      'VoxelLibrary'
                if (reference && reference->unreference()) {
                                          ^
core/reference.h:308:3: note: in instantiation of member function
      'Ref<VoxelLibrary>::unref' requested here
                unref();
                ^
modules/voxel/voxel_mesher.h:12:7: note: in instantiation of member function
      'Ref<VoxelLibrary>::~Ref' requested here
class VoxelMesher : public Reference {
      ^
core/reference.h:292:4: note: in instantiation of function template
      specialization 'memdelete<VoxelMesher>' requested here
                        memdelete(reference);
                        ^
core/reference.h:87:3: note: in instantiation of member function
      'Ref<VoxelMesher>::unref' requested here
                unref();
                ^
core/reference.h:223:3: note: in instantiation of member function
      'Ref<VoxelMesher>::ref' requested here
                ref(p_from);
                ^
modules/voxel/voxel_terrain.h:30:44: note: in instantiation of member function
      'Ref<VoxelMesher>::Ref' requested here
    Ref<VoxelMesher> get_mesher() { return _mesher; }
                                           ^
modules/voxel/voxel.h:6:7: note: forward declaration of 'VoxelLibrary'
class VoxelLibrary;```

**Comment by Zylann** [comment]
Yeah that's the same thing... did you tried to use inline or .cpp implementation?
Another try, put `#include "voxel_library.h"` as the last include in voxel_terrain.cpp?

**Comment by cyian-1756** [comment]
> What happens if you prepend _FORCE_INLINE_ to get_mesher()?

Mind explaining what that is/how to do it? (I'm really not a C++ person)

**Comment by Zylann** [comment]
Replace this line:
```cpp
    Ref<VoxelMesher> get_mesher() { return _mesher; }
```
By this:
```cpp
    _FORCE_INLINE_ Ref<VoxelMesher> get_mesher() { return _mesher; }
```
But I'm not sure on this one.

Try this first;
In voxel_mesher.h, add this after all the `#include`s:
```cpp
#include "voxel_library.h"
```

**Comment by cyian-1756** [comment]
@Zylann That seems to have fixed it (Adding #include "voxel_library.h"), Godot compiles and runs. Thanks for the help!
