### ISSUE TITLE
Compile fails after e3abe2f

### ISSUE THREAD

**Issue by menip** [Zylann/godot_voxel#165]
e3abe2f added a new function, `int VoxelStreamFile::get_used_channels_mask()`, and I'm no longer able to successfully compile. I'm guessing it's because nothing is returned if the if condition fails. Now, it is a warning that is being treated as an error, but if this is default Godot scons script, and not just my system, it should probably be addressed. 
Error:

> modules/voxel/streams/voxel_stream_file.cpp: In member function 'virtual int VoxelStreamFile::get_used_channels_mask() const':
modules/voxel/streams/voxel_stream_file.cpp:53:1: error: control reaches end of non-void function [-Werror=return-type]

https://github.com/Zylann/godot_voxel/blob/a24b33eca1e2373dad3236edbe104fd5f5f28d61/streams/voxel_stream_file.cpp#L49-L53

**Comment by Zylann** [comment]
I hate msvc

**Comment by Zylann** [comment]
Should be fixed by b95f47b0181c38348f7f95793ee61a56cbe347dd
