### ISSUE TITLE
Build errors with linux & macos editor

### ISSUE THREAD

**Issue by Trey2k** [Zylann/godot_voxel#501]
We have our engine rebuild every night for each platform and this evening it failed on the linux and macos editor builds. Below is the errors we got.
Linux:
```
...
In file included from modules/voxel/editor/terrain/editor_property_aabb_min_max.h:6,
                 from modules/voxel/editor/terrain/editor_property_aabb_min_max.cpp:1:
modules/voxel/editor/terrain/../../util/godot/classes/editor_spin_slider.h:5:10: fatal error: editor/gui/editor_spin_slider.h: No such file or directory
    5 | #include <editor/gui/editor_spin_slider.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [modules/voxel/editor/terrain/editor_property_aabb_min_max.linuxbsd.editor.double.x86_64.SP.o] Error 1
In file included from modules/voxel/editor/terrain/editor_property_aabb_min_max.h:6,
                 from modules/voxel/editor/terrain/voxel_terrain_editor_inspector_plugin.cpp:5:
modules/voxel/editor/terrain/../../util/godot/classes/editor_spin_slider.h:5:10: fatal error: editor/gui/editor_spin_slider.h: No such file or directory
    5 | #include <editor/gui/editor_spin_slider.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [modules/voxel/editor/terrain/voxel_terrain_editor_inspector_plugin.linuxbsd.editor.double.x86_64.SP.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:05:07.158]
```
MacOS:
```
...
In file included from modules/voxel/editor/terrain/editor_property_aabb_min_max.cpp:1:
In file included from modules/voxel/editor/terrain/editor_property_aabb_min_max.h:6:
modules/voxel/editor/terrain/../../util/godot/classes/editor_spin_slider.h:5:10: fatal error: 'editor/gui/editor_spin_slider.h' file not found
#include <editor/gui/editor_spin_slider.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [modules/voxel/editor/terrain/editor_property_aabb_min_max.macos.editor.double.x86_64.o] Error 1
In file included from modules/voxel/editor/terrain/voxel_terrain_editor_inspector_plugin.cpp:5:
In file included from modules/voxel/editor/terrain/editor_property_aabb_min_max.h:6:
modules/voxel/editor/terrain/../../util/godot/classes/editor_spin_slider.h:5:10: fatal error: 'editor/gui/editor_spin_slider.h' file not found
#include <editor/gui/editor_spin_slider.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [modules/voxel/editor/terrain/voxel_terrain_editor_inspector_plugin.macos.editor.double.x86_64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:06:13.474]
```
Windows however did build successfully. 
Some more info - we are building godot from the current 4.0 branch (16a6bdd)

**Comment by Trey2k** [comment]
Looks like this is caused by e9c556c4a01c159b5df7381e5febf3badc38bd4d, which is fixing upstream changes. However these changes have not made it into the 4.0 branch yet. Now that 4.0 has a stable release with a branch to track would it not make more sense to track that for development? As given the choice I would rather my builds come from there.

**Comment by MGilleronFJ** [comment]
The master branch of the voxel module builds against the master branch of Godot. If you want a version that is known to build for a specific version of Godot, you can use the snapshot branches, which track what the state of the module was when Godot versions get released (most recent is `godot4.0`, which builds against whatever commit corresponds to 4.0 in Godot. Might also build fine for some time after that).

**Comment by Trey2k** [comment]
> The master branch of the voxel module builds against the master branch of Godot. If you want a version that is known to build for a specific version of Godot, you can use the snapshot branches, which track what the state of the module was when Godot versions get released (most recent is godot4.0, which builds against whatever commit corresponds to 4.0 in Godot. Might also build fine for some time after that).

Got it, I did not see there was a godot4.0 branch. That being said its 37 commits behind currently and I know we are using features recently added. IE for the shadows. And I am sure there will be updates we need in the future too. Is there any plan for to be updated with master or will it remain stale? If the latter then I guess we will have no choice but to build with master.

> If your MacOS build fails but your Windows build doesn't, it sounds like a red flag. The error isn't OS-specific, so not sure why you build against different version of Godot.

As for windows, they actually did fail too, our actions seem to report success wrongfully.

**Comment by Trey2k** [comment]
> I have only done snapshot branches for major and minor releases which I don't update so far, because I don't have the bandwidth to maintain a branch for every Godot version and merging all the latest features in each of them.

I completely understand, I would just go to the master godot branch but all the other modules we use just track 4.0 so then we will start having the issue in reverse. Either way this isnt a bug its our issue to deal with. Apricate the info.
