### ISSUE TITLE
Build Error on macOS

### ISSUE THREAD

**Issue by sclausen** [Zylann/godot_voxel#288]
I'm trying to build on macOS 11.4 with scons 4.1.0 and get the following error:

godot: 3.2
Commit: godotengine/godot@2407df9870cb66d38c6d3523f4ed27ae3bb3c3fd

godot_voxel: 3.2.3
Commit: 603357eb594bf4f21e8a15cc72cfc5bfefa1a6ef

```
[…]
[Initial build] Compiling ==> modules/voxel/util/utility.cpp
[Initial build] Compiling ==> modules/voxel/util/zprofiling.cpp
[Initial build] Compiling ==> modules/voxel/terrain/voxel_block.cpp
modules/voxel/generators/graph/voxel_graph_runtime.cpp:477:40: error: conversion from 'unsigned long' to 'const Variant' is ambiguous
                                                  .format(varray(_program.size() * sizeof(float), _memory.size() * sizeof(float))));
                                                                 ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
modules/voxel/generators/graph/../../util/macros.h:10:14: note: expanded from macro 'PRINT_VERBOSE'
                print_line(msg);                            \
                           ^~~
./core/variant.h:251:2: note: candidate constructor
        Variant(bool p_bool);
        ^
./core/variant.h:252:2: note: candidate constructor
        Variant(signed int p_int); // real one
        ^
./core/variant.h:253:2: note: candidate constructor
[Initial build] gned int p_int);
        ^
./core/variant.h:259:2: note: candidate constructor
        Variant(signed short p_short); // real one
        ^
./core/variant.h:260:2: note: candidate constructor
        Variant(unsigned short p_short);
        ^
./core/variant.h:261:2: note: candidate constructor
        Variant(signed char p_char); // real one
        ^
./core/variant.h:262:2: note: candidate constructor
        Variant(unsigned char p_char);
        ^
./core/variant.h:263:2: note: candidate constructor
        Variant(int64_t p_int); // real one
        ^
./core/variant.h:264:2: note: candidate constructor
        Variant(uint64_t p_int);
        ^
./core/variant.h:265:2: note: candidate constructor
        Variant(float p_float);
        ^
./core/variant.h:266:2: note: candidate constructor
        Variant(double p_double);
        ^
[Initial build] Compiling ==> modules/voxel/terrain/voxel_box_mover.cpp
[Initial build] Compiling ==> modules/voxel/terrain/voxel_data_loader.cpp
[Initial build] Compiling ==> modules/voxel/terrain/voxel_lod_terrain.cpp
1 error generated.
scons: *** [modules/voxel/generators/graph/voxel_graph_runtime.osx.tools.x86_64.o] Error 1
scons: building terminated because of errors.
scons platform=osx arch=x86_64 --jobs=$(sysctl -n hw.logicalcpu)  722,69s user 73,52s system 584% cpu 2:16,32 total
```

**Comment by Zylann** [comment]
Which version did you try to compile? I cannot find the code referred by your log.

**Comment by sclausen** [comment]
I attached the commits of godot and godot_voxel under the error log.

**Comment by Zylann** [comment]
Ooops indeed you did.
It's a very old commit... that must have been fixed for a while now. Do you need this version specifically?

**Comment by sclausen** [comment]
I didn't needed that old version, but with 3.3, I've got the same error. Am I still using too old versions?
The last commit on your godot4 branch is one year old, so is your master for godot3, or already for godot4?

Anyway, here is the output of the usage of the latest 3.x branches of both projects:

godot:https://github.com/godotengine/godot/commit/64cfd5cbaaa7a71283d460456ab098092da39fab
godot_voxel 3.3: 0dc6702

```
[Initial build] Compiling ==> modules/voxel/generators/voxel_generator.cpp
[Initial build] Compiling ==> modules/voxel/generators/graph/program_graph.cpp
modules/voxel/streams/region/region_file.cpp:657:26: error: conversion from 'size_t' (aka 'unsigned long') to 'const Variant' is ambiguous
                                                           .format(varray(lut_index, position.to_vec3(), block_begin, file_len)));
                                                                          ^~~~~~~~~
./core/variant.h:261:2: note: candidate constructor
        Variant(bool p_bool);
        ^
./core/variant.h:262:2: note: candidate constructor
        Variant(signed int p_int); // real one
        ^
./core/variant.h:263:2: note: candidate constructor
        Variant(unsigned int p_int);
        ^
./core/variant.h:269:2: note: candidate constructor
        Variant(signed short p_short); // real one
        ^
./core/variant.h:270:2: note: candidate constructor
        Variant(unsigned short p_short);
        ^
./core/variant.h:271:2: note: candidate constructor
        Variant(signed char p_char); // real one
        ^
./core/variant.h:272:2: note: candidate constructor
        Variant(unsigned char p_char);
        ^
./core/variant.h:273:2: note: candidate constructor
        Variant(int64_t p_int); // real one
        ^
./core/variant.h:274:2: note: candidate constructor
        Variant(uint64_t p_int);
        ^
./core/variant.h:275:2: note: candidate constructor
        Variant(float p_float);
        ^
./core/variant.h:276:2: note: candidate constructor
        Variant(double p_double);
        ^
modules/voxel/streams/region/region_file.cpp:666:26: error: conversion from 'size_t' (aka 'unsigned long') to 'const Variant' is ambiguous
                                                           .format(varray(lut_index, position.to_vec3(), block_data_size, remaining_size)));
                                                                          ^~~~~~~~~
./core/variant.h:261:2: note: candidate constructor
        Variant(bool p_bool);
        ^
./core/variant.h:262:2: note: candidate constructor
        Variant(signed int p_int); // real one
        ^
./core/variant.h:263:2: note: candidate constructor
        Variant(unsigned int p_int);
        ^
./core/variant.h:269:2: note: candidate constructor
        Variant(signed short p_short); // real one
        ^
./core/variant.h:270:2: note: candidate constructor
        Variant(unsigned short p_short);
        ^
./core/variant.h:271:2: note: candidate constructor
        Variant(signed char p_char); // real one
        ^
./core/variant.h:272:2: note: candidate constructor
        Variant(unsigned char p_char);
        ^
./core/variant.h:273:2: note: candidate constructor
        Variant(int64_t p_int); // real one
        ^
./core/variant.h:274:2: note: candidate constructor
        Variant(uint64_t p_int);
        ^
./core/variant.h:275:2: note: candidate constructor
        Variant(float p_float);
        ^
./core/variant.h:276:2: note: candidate constructor
        Variant(double p_double);
        ^
[Initial build] Compiling ==> modules/voxel/generators/graph/range_utility.cpp
[Initial build] Compiling ==> modules/voxel/generators/graph/voxel_generator_graph.cpp
[Initial build] Compiling ==> modules/voxel/generators/graph/voxel_graph_node_db.cpp
2 errors generated.
scons: *** [modules/voxel/streams/region/region_file.osx.tools.x86_64.o] Error 1
In file included from modules/voxel/generators/graph/voxel_graph_node_db.cpp:1:
In file included from modules/voxel/generators/graph/voxel_graph_node_db.h:4:
In file included from modules/voxel/generators/graph/voxel_generator_graph.h:6:
modules/voxel/generators/graph/voxel_graph_runtime.h:184:29: warning: private field '_node' is not used [-Wunused-private-field]
                const ProgramGraph::Node &_node;
                                          ^
In file included from modules/voxel/generators/graph/voxel_generator_graph.cpp:1:
In file included from modules/voxel/generators/graph/voxel_generator_graph.h:6:
modules/voxel/generators/graph/voxel_graph_runtime.h:184:29: warning: private field '_node' is not used [-Wunused-private-field]
                const ProgramGraph::Node &_node;
                                          ^
1 warning generated.
1 warning generated.
scons: building terminated because of errors.
scons platform=osx arch=x86_64 --jobs=$(sysctl -n hw.logicalcpu)  674,07s user 72,34s system 420% cpu 2:57,31 total
```

**Comment by sclausen** [comment]
I tried to use the master of both repositories, but your master uses e.g. `core/pool_vector.h`, which is just available in the 3.x branches of godot.
Using godot 3.x and your master worked! 🥳 

Albeit your last commit to your godo4 branch is more than a year old, that would be the current state of development for godot4, right? Are you planning on working to support godot 4 in the future, or do you want to only develop for 3.x?

**Comment by Zylann** [comment]
Using Godot 3.2 or 3.3 should not make much difference, the fix to that issue was done in my module. I haven't ported to Godot 4 yet so the master branch is still compatible with Godot 3.3.

**Comment by sclausen** [comment]
I tried to use the master of both repositories, but your master uses e.g. core/pool_vector.h, which is just available in the 3.x branches of godot.
Using godot 3.x and your master worked! 🥳

Albeit your last commit to your godo4 branch is more than a year old, that would be the current state of development for godot4, right? Are you planning on working to support godot 4 in the future, or do you want to only develop for 3.x?

**Comment by Zylann** [comment]
My master branch tracks Godot's 3.x branch.
My godot4 branch is an old attempt which I havent updated in a very long time (and I should delete it).
I plan to switch to Godot 4 once it starts to become usable.
